package mock

import (
	"context"
	"time"

	"github.com/hrygo/echomind/pkg/ai"
)

type MockProvider struct {
	dimensions int
}

func NewProvider() *MockProvider {
	return &MockProvider{dimensions: 1024} // Default to 1024 dimensions
}

func NewProviderWithDimensions(dimensions int) *MockProvider {
	return &MockProvider{dimensions: dimensions}
}

// AIProvider implementation

func (m *MockProvider) Summarize(ctx context.Context, text string) (ai.AnalysisResult, error) {
	return ai.AnalysisResult{
		Summary:     "This is a mock summary of the email.",
		Category:    "Work",
		Sentiment:   "Neutral",
		Urgency:     "Medium",
		ActionItems: []string{"Mock action item 1", "Mock action item 2"},
		SmartActions: []ai.SmartAction{
			{
				Type:  "calendar_event",
				Label: "Add to Calendar",
				Data:  map[string]string{"title": "Mock Meeting", "start": "2023-11-25 10:00"},
			},
			{
				Type:  "create_task",
				Label: "Create Task",
				Data:  map[string]string{"title": "Review Document", "due": "2023-11-26"},
			},
		},
	}, nil
}

func (m *MockProvider) Classify(ctx context.Context, text string) (string, error) {
	return "Work", nil
}

func (m *MockProvider) AnalyzeSentiment(ctx context.Context, text string) (ai.SentimentResult, error) {
	return ai.SentimentResult{
		Sentiment: "Neutral",
		Urgency:   "Medium",
	}, nil
}

func (m *MockProvider) GenerateDraftReply(ctx context.Context, emailContent, userPrompt string) (string, error) {
	return "Dear User,\n\nThis is a mock reply generated by the system.\n\nBest regards,\nMock AI", nil
}

func (m *MockProvider) StreamChat(ctx context.Context, messages []ai.Message, ch chan<- ai.ChatCompletionChunk) error {
	defer close(ch)

	words := []string{"This ", "is ", "a ", "simulated ", "streaming ", "response ", "from ", "the ", "Mock ", "Provider. ", "I ", "can ", "answer ", "your ", "questions ", "about ", "emails!"}

	for _, word := range words {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
			// Simulate network delay
			time.Sleep(50 * time.Millisecond)

			chunk := ai.ChatCompletionChunk{
				ID: "mock-id",
				Choices: []ai.Choice{
					{
						Index: 0,
						Delta: ai.DeltaContent{Content: word},
					},
				},
			}
			ch <- chunk
		}
	}
	return nil
}

// EmbeddingProvider implementation

func (m *MockProvider) Embed(ctx context.Context, text string) ([]float32, error) {
	// Return a vector with the configured dimensions
	vec := make([]float32, m.dimensions)
	for i := range vec {
		vec[i] = 0.01 // Dummy value
	}
	// Simulate latency
	time.Sleep(100 * time.Millisecond)
	return vec, nil
}

func (m *MockProvider) EmbedBatch(ctx context.Context, texts []string) ([][]float32, error) {
	var results [][]float32
	for range texts {
		vec, _ := m.Embed(ctx, "")
		results = append(results, vec)
	}
	return results, nil
}

func (m *MockProvider) GetDimensions() int {
	return m.dimensions
}
